### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by opus1269** [benjaminRomano/gulp-manager#3]
Is it possible to set the font size in the output pane? If not, could you add an option? Too small for my old eyes.

**Comment by benjaminRomano** [comment]
I made the output window inherit the font-size from the current atom theme. Does this make it better?

**Comment by opus1269** [comment]
After the update and a restart I did not see any difference (was still 12px).  By setting this, I was able to achieve the  effect I was looking for:

``` css
    // style the gulp-pane output
   .gulp-pane .output-view .output-container pre {
       font-size: 15px;
   }
```

Really love the package!
